site_name: ullm Documentation
site_description: Lightweight, fast alternative to litellm - unified interface for LLMs
site_author: ullm contributors
site_url: https://silvestrid.github.io/ullm/
repo_url: https://github.com/silvestrid/ullm
repo_name: silvestrid/ullm
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            members_order: source
            merge_init_into_class: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Basic Usage: getting-started/basic-usage.md
  - User Guide:
    - Overview: guide/overview.md
    - Providers: guide/providers.md
    - Streaming: guide/streaming.md
    - Tool Calling: guide/tool-calling.md
    - Structured Output: guide/structured-output.md
    - Error Handling: guide/error-handling.md
    - DSPy Integration: guide/dspy-integration.md
  - API Reference:
    - Completion API: api/completion.md
    - Responses API: api/responses.md
    - Types: api/types.md
    - Exceptions: api/exceptions.md
  - Architecture:
    - Design Decisions: architecture/decisions.md
    - Client Registry: architecture/registry.md
    - Provider System: architecture/providers.md
  - Development:
    - Contributing: development/contributing.md
    - Development Setup: development/setup.md
    - Release Process: development/releases.md
    - Testing: development/testing.md
  - Changelog: changelog.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/silvestrid/ullm
  version:
    provider: mike
